variables:
    GIT_SUBMODULE_STRATEGY: recursive

pages:
  tags:
    - docker
    - pages
  only:
    - master
  image: boileaum/jupyter
  script:
    - makefile
    - mv build public
  artifacts:
    paths:
      - public
