variables:
    GIT_SUBMODULE_STRATEGY: recursive

pages:
  tags:
    - docker
    - pages
  only:
    - master
  image: boileaum/debian-jupyter
  script:
    - mkdir public
    - scripts/make_slides.sh
    - scripts/make_archive.sh --zip
  artifacts:
    paths:
      - public
