variables:
    GIT_SUBMODULE_STRATEGY: recursive

pages:
  tags:
    - docker
    - pages
  only:
    - master
  image: jupyter/minimal-notebook
  script:
    - mkdir public
      #- scripts/make_slides.sh
      #- scripts/make_archive.sh --zip
    - pandoc -f markdown_mmd index.md -t html -o public/index.html
  artifacts:
    paths:
      - public
